#
# COPY A FILE TO A TARGET DESTINATION
#

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: copy-file
spec:
  workspaces:
  - name: workspace
    description: |
      The target folder for checking out git repositories.
    mountPath: /workspace
  params:
  - name: image
    description: The docker image used for executing the script (the ci base image)
    default: "julianweberdev/ubuntu-ci-minimal:latest"

  - name: source-file-path
    description: the source file location
    type: string
  - name: target-file-path
    description: the target file location
    type: string

  steps:
    - name: copy-file
      resources:
        requests:
          memory: 50Mi
          cpu: 50m
        limits:
          memory: 100Mi
          cpu: 100m
      image: "$(params.image)"
      env:
        - name: SOURCE_FILE_PATH
          value: "$(params.source-file-path)"
        - name: TARGET_FILE_PATH
          value: "$(params.target-file-path)"
      script: |
        #!/usr/bin/env bash
        set -ue

        echo "#################################"
        echo "USER: $(whoami)"
        echo "HOME: $HOME"
        echo "CURRENT PATH: $(pwd)"

        echo "Copying $SOURCE_FILE_PATH -> $TARGET_FILE_PATH"
        cp "$SOURCE_FILE_PATH" "$TARGET_FILE_PATH"