apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-secret-from-json
spec:
  workspaces:
  - name: workspace
    description: |
      The workspace folder with the automation repository including platform_config.
    mountPath: /workspace

  params:
    - name: image
      description: The docker image used for executing the script (the ci base image)
      default: "julianweberdev/ubuntu-ci-minimal:latest"

    - name: target-namespace
      description: The namespace where the secret should be created
      type: string
    - name: secret-name
      description: A name for the secret that should be created
      type: string
    - name: json-file-location
      description: The file location of the json file that should be used as input for creating the secret
    - name: automation-git-project-name
      description: e.g. kubementat
      type: string

  steps:
    - name: create-secret
      resources:
        requests:
          memory: 50Mi
          cpu: 50m
        limits:
          memory: 100Mi
          cpu: 200m
      image: "$(params.image)"
      env:
        - name: TARGET_NAMESPACE
          value: "$(params.target-namespace)"
        - name: SECRET_NAME
          value: "$(params.secret-name)"
        - name: JSON_FILE_LOCATION
          value: "$(params.json-file-location)"
        - name: PATH_TO_SCRIPT
          value: "/workspace/$(params.automation-git-project-name)/utilities/secret_management/create_secret_from_json.sh"
      script: |
        #!/usr/bin/env bash
        set -ue

        JSON="$(cat $JSON_FILE_LOCATION)"
        ./$PATH_TO_SCRIPT "$TARGET_NAMESPACE" "$SECRET_NAME" "$JSON"