apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mvn-package
spec:
  workspaces:
  - name: workspace
    description: |
      The workspace folder to list files.
    mountPath: /workspace
  params:
    - name: image
      default: "maven:3.8.4-openjdk-17-slim"
      description: |
        The image url with tag to use as image for the mvn package execution

    - name: build-subdirectory
      description: the build sub-directory for executing mvn in
    - name: additional-arguments
      description: "A list of additional arguments to add to the mvn package command"
      default: ""
    - name: skip-tests
      description: Should the tests be skipped (true/false)
      default: "false"
    - name: maven-opts
      description: MAVEN_OPTS configuration string
      default: ""
  steps:
    - name: mvn-package
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
        limits:
          memory: 2Gi
          cpu: 1500m
      image: "$(params.image)"
      env:
        - name: WORKSPACE_PATH
          value: "$(workspaces.workspace.path)"
        - name: BUILD_SUBDIRECTORY
          value: "$(params.build-subdirectory)"
        - name: ADDITIONAL_ARGUMENTS
          value: "$(params.additional-arguments)"
        - name: SKIP_TESTS
          value: "$(params.skip-tests)"
        - name: MAVEN_OPTS
          value: "$(params.maven-opts)"
      script: |
        #!/usr/bin/env bash
        set -ue
        echo "#####################"
        echo "MAVEN VERSION:"
        mvn --version
        echo "#####################"

        echo "WORKSPACE_PATH: $WORKSPACE_PATH"
        echo "BUILD_SUBDIRECTORY: $BUILD_SUBDIRECTORY"
        echo "ADDITIONAL_ARGUMENTS: $ADDITIONAL_ARGUMENTS"
        echo "SKIP_TESTS: $SKIP_TESTS"
        echo "MAVEN_OPTS: $MAVEN_OPTS"

        cd $WORKSPACE_PATH/$BUILD_SUBDIRECTORY
        echo "CURRENT PATH: $(pwd)"

        additional_arguments="$ADDITIONAL_ARGUMENTS"
        if [ "$SKIP_TESTS" == "true" ]; then
          additional_arguments="${additional_arguments} -DskipTests"
        fi

        echo "Executing mvn command: mvn $additional_arguments package"
        mvn $additional_arguments package