apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline-flutter-example-run
spec:
  # here we need to use our previously created service account (see setup_pipelines.sh)
  # as we are deploying to another namespace than the tekton pipeline
  # and want to grant according permissions for the helm deploy task
  serviceAccountName: "HELM_DEPLOYER_SERVICE_ACCOUNT_NAME_PLACEHOLDER"
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: STORAGE_CLASS_PLACEHOLDER
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              # HINT: TODO: ADJUST ME IF MORE SPACE IS NEEDED FOR THE PIPELINE TO RUN
              storage: 100Mi
  pipelineRef:
    name: build-pipeline-flutter-example
  timeout: 25m
  params:
    - name: environment
      value: dev
    - name: team
      value: "testing"
    - name: docker-registry-base-url
      value: "DOCKER_REGISTRY_BASE_URL_PLACEHOLDER"
    - name: tekton-ci-image-name
      value: "TEKTON_CI_IMAGE_NAME_PLACEHOLDER"
    - name: tekton-ci-image-tag
      value: "TEKTON_CI_IMAGE_TAG_PLACEHOLDER"

    - name: automation-git-project-name
      value: "AUTOMATION_GIT_PROJECT_NAME_PLACEHOLDER"
    - name: automation-git-revision
      value: "AUTOMATION_GIT_REVISION_PLACEHOLDER"
    - name: automation-git-server-host
      value: "AUTOMATION_GIT_SERVER_HOST_PLACEHOLDER"
    - name: automation-git-server-port
      value: "AUTOMATION_GIT_SERVER_PORT_PLACEHOLDER"
    - name: automation-git-server-ssh-user
      value: "AUTOMATION_GIT_SERVER_SSH_USER_PLACEHOLDER"
    - name: automation-git-url
      value: "AUTOMATION_GIT_URL_PLACEHOLDER"

    - name: docker-build-context-subpath
      value: "./"
    - name: push-image-name
      value: "flutter-example"
    - name: push-image-tag
      value: "testing"
    - name: set-tag-from-version-file
      value: "false"