apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: deploy-pipeline-nginx-reverse-proxy-run
spec:
  # here we need to use our previously created service account (see setup_pipelines.sh)
  # as we are deploying to another namespace than the tekton pipeline
  # and want to grant according permissions for the helm deploy task
  serviceAccountName: helm-deployer-sa
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: STORAGE_CLASS_PLACEHOLDER
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
  pipelineRef:
    name: deploy-pipeline-nginx-reverse-proxy
  timeout: 10m
  params:
    - name: environment
      value: dev
    - name: team
      value: "dev1"
    - name: docker-registry-base-url
      value: "DOCKER_REGISTRY_BASE_URL_PLACEHOLDER"
