################################
# This pipeline builds the ci images used for automating our tekton pipeline tasks
# See push-image-tag and push-image-url for target registry location
################################

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline-ci-images
spec:
  params:
    # Platform config
    - name: docker-registry-base-url
      description: The docker registry base url with path to load the CI image for tekton task execution from
    - name: tekton-ci-image-name
      description: The image name to use for the automation run
      default: "ubuntu-ci-minimal"
    - name: tekton-ci-image-tag
      description: The image tag to use for the automation run
      default: "latest"

    # AUTOMATION REPOSITORY SECTION
    - name: automation-git-url
      description: |
        The git url of the automation repository to use (your fork of the easy_tekton repos address)
        e.g.: if you would use the easy_tekton default location: ssh://git@github.com:julweber/easy_tekton.git
    - name: automation-git-project-name
      description: |
        your local directory name for the repository
        this should be set to "easy_tekton" despite you change a lot of code in this repo ;)
      default: "easy_tekton"
    - name: automation-git-revision
      description: |
        the git revision to checkout
        for the automation repository we are using master most of the time
      default: "master"
    - name: automation-git-server-host
      description: |
        this should match the hostname provided in automation-git-url
        this setting is used for configuring the ssh auth mechanism correctly
        e.g.: github.com
    - name: automation-git-server-port
      description: |
        the git server ssh port
        this should match the port provided (or 22 if no port is provided) in automation-git-url
        this setting is used for configuring the ssh auth mechanism correctly
      default: "22"
    - name: automation-git-server-ssh-user
      description: |
        the git server ssh user
        this should match the username provided in automation-git-url
        this setting is used for configuring the ssh auth mechanism correctly
      default: "git"
    - name: automation-git-crypt-unlock
      description: |
        should a git-crypt unlock be executed on the checked out repo?
      default: "false"

  workspaces:
    - name: pipeline-workspace
  tasks:

    # clone automation source repo for build
    - name: git-clone-automation
      taskRef:
        name: git-clone-with-ssh-auth
      params:
        - name: git-url
          value: "$(params.automation-git-url)"
        - name: git-project-name
          value: "$(params.automation-git-project-name)"
        - name: git-revision
          value: "$(params.automation-git-revision)"
        - name: git-server-host
          value: "$(params.automation-git-server-host)"
        - name: git-server-port
          value: "$(params.automation-git-server-port)"
        - name: git-server-ssh-user
          value: "$(params.automation-git-server-ssh-user)"
        - name: git-crypt-unlock
          value: "$(params.automation-git-crypt-unlock)"
        - name: docker-registry-base-url
          value: "$(params.docker-registry-base-url)"
        - name: tekton-ci-image-name
          value: "$(params.tekton-ci-image-name)"
        - name: tekton-ci-image-tag
          value: "$(params.tekton-ci-image-tag)"
      workspaces:
        - name: workspace
          workspace: pipeline-workspace

    # list workspace contents
    - name: list-workspace-contents
      runAfter:
        - git-clone-automation
      taskRef:
        name: list-workspace
      params:
        - name: docker-registry-base-url
          value: "$(params.docker-registry-base-url)"
        - name: tekton-ci-image-name
          value: "$(params.tekton-ci-image-name)"
        - name: tekton-ci-image-tag
          value: "$(params.tekton-ci-image-tag)"
      workspaces:
        - name: workspace
          workspace: pipeline-workspace

    # build docker image ubuntu-ci-minimal
    - name: build-docker-image-ubuntu-minimal
      retries: 2
      runAfter:
        - git-clone-automation
      taskRef:
        name: build-and-push-docker-image
      params:
        - name: path-to-context
          value: "/workspace/easy_tekton/docker_files/ci_images/ubuntu_ci_minimal"
        - name: path-to-dockerfile-within-context
          value: Dockerfile
        - name: push-image-url
          value: "$(params.docker-registry-base-url)/ubuntu-ci-minimal"
        - name: push-image-tag
          value: latest
      workspaces:
        - name: workspace
          workspace: pipeline-workspace

    # build docker base image ubuntu-ci
    - name: build-docker-image-ubuntu-ci
      retries: 2
      runAfter:
        - build-docker-image-ubuntu-minimal
      taskRef:
        name: build-and-push-docker-image
      params:
        - name: path-to-context
          value: "/workspace/easy_tekton/docker_files/ci_images/ubuntu_ci"
        - name: path-to-dockerfile-within-context
          value: Dockerfile
        - name: push-image-url
          value: "$(params.docker-registry-base-url)/ubuntu-ci"
        - name: push-image-tag
          value: latest
      workspaces:
        - name: workspace
          workspace: pipeline-workspace
