# This pipeline serves for test purposes and checks whether the general pipeline execution (without workspace/volume usage) is working as expected
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  params:
    - name: docker-registry-base-url
      description: The docker registry base url with path to load the CI image for tekton task execution from
    - name: tekton-ci-image-name
      description: The image name to use for the automation run
      default: "ubuntu-ci-minimal"
    - name: tekton-ci-image-tag
      description: The image tag to use for the automation run
      default: "latest"

  tasks:
    - name: echo-hello-world
      taskRef:
        name: echo
      params:
        - name: echo-message
          value: "Hello World! I am running from tekton!"
        - name: docker-registry-base-url
          value: "$(params.docker-registry-base-url)"
        - name: tekton-ci-image-name
          value: "$(params.tekton-ci-image-name)"
        - name: tekton-ci-image-tag
          value: "$(params.tekton-ci-image-tag)"