################################
# This pipeline deploys a mysql backing service instance for an environment and team
# See team and environment for details of the deployment
# It also initializes the database tables configured in platform_config's MYSQL_DATABASE_CONFIGURATION
################################

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: setup-pipeline-mysql
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: environment
      type: string
      description: The name of the app environment (e.g. dev)
      # default: dev
    - name: team
      type: string
      description: The name of the team to run the pipeline for. Results in mysql deployment namespace

    # Platform configuration
    - name: docker-registry-base-url
      description: The docker registry base url with path to load the CI image for tekton task execution from
    - name: tekton-ci-image-name
      description: The image name to use for the automation run
      default: "ubuntu-ci-minimal"
    - name: tekton-ci-image-tag
      description: The image tag to use for the automation run
      default: "latest"

    # AUTOMATION REPOSITORY SECTION
    - name: automation-git-url
      description: |
        The git url of the automation repository to use (your fork of the kubementat repos address)
        e.g.: if you would use the kubementat default location: ssh://git@github.com:Kubementat/kubementat.git
    - name: automation-git-project-name
      description: |
        your local directory name for the repository
        In general this can be set to the default: "kubementat"
      default: "kubementat"
    - name: automation-git-revision
      description: |
        the git revision to checkout
        for the automation repository we are using master most of the time
      default: "master"
    - name: automation-git-server-host
      description: |
        this should match the hostname provided in automation-git-url
        this setting is used for configuring the ssh auth mechanism correctly
        e.g.: github.com
    - name: automation-git-server-port
      description: |
        the git server ssh port
        this should match the port provided (or 22 if no port is provided) in automation-git-url
        this setting is used for configuring the ssh auth mechanism correctly
      default: "22"
    - name: automation-git-server-ssh-user
      description: |
        the git server ssh user
        this should match the username provided in automation-git-url
        this setting is used for configuring the ssh auth mechanism correctly
      default: "git"
    - name: automation-git-crypt-unlock
      description: |
        should a git-crypt unlock be executed on the checked out repo?
      default: "true"

  tasks:

    # clone automation source repo for deploy steps
    - name: git-clone-automation
      taskRef:
        name: git-clone-with-ssh-auth
      params:
        - name: git-url
          value: "$(params.automation-git-url)"
        - name: git-project-name
          value: "$(params.automation-git-project-name)"
        - name: git-revision
          value: "$(params.automation-git-revision)"
        - name: git-server-host
          value: "$(params.automation-git-server-host)"
        - name: git-server-port
          value: "$(params.automation-git-server-port)"
        - name: git-server-ssh-user
          value: "$(params.automation-git-server-ssh-user)"
        - name: git-crypt-unlock
          value: "$(params.automation-git-crypt-unlock)"
        - name: docker-registry-base-url
          value: "$(params.docker-registry-base-url)"
        - name: tekton-ci-image-name
          value: "$(params.tekton-ci-image-name)"
        - name: tekton-ci-image-tag
          value: "$(params.tekton-ci-image-tag)"
      workspaces:
        - name: workspace
          workspace: pipeline-workspace

    # deploy mysql via helm
    - name: deploy-mysql
      runAfter:
        - git-clone-automation
      taskRef:
        name: run-automation-script-for-environment
      params:
        - name: docker-registry-base-url
          value: "$(params.docker-registry-base-url)"
        - name: tekton-ci-image-name
          value: "$(params.tekton-ci-image-name)"
        - name: tekton-ci-image-tag
          value: "$(params.tekton-ci-image-tag)"
        - name: path-to-automation-script
          value: "/workspace/$(params.automation-git-project-name)/tekton_ci/scripts/install_mysql_helm_chart.sh"
        - name: environment
          value: "$(params.environment)"
        - name: team
          value: "$(params.team)"
      workspaces:
        - name: workspace
          workspace: pipeline-workspace

    # setup mysql database configuration
    - name: setup-mysql
      runAfter:
        - deploy-mysql
      taskRef:
        name: run-automation-script-for-environment
      params:
        - name: docker-registry-base-url
          value: "$(params.docker-registry-base-url)"
        - name: tekton-ci-image-name
          value: "$(params.tekton-ci-image-name)"
        - name: tekton-ci-image-tag
          value: "$(params.tekton-ci-image-tag)"
        - name: path-to-automation-script
          value: "/workspace/$(params.automation-git-project-name)/tekton_ci/scripts/setup_mysql_databases.sh"
        - name: environment
          value: "$(params.environment)"
        - name: team
          value: "$(params.team)"
      workspaces:
        - name: workspace
          workspace: pipeline-workspace