################################
# This pipeline copies a docker image from one registry to another via skopeo
################################

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sync-docker-images-pipeline
spec:
  params:
    # env and team
    - name: environment
      type: string
      description: The name of the environment to run the pipeline for. (e.g. dev, prod)
      default: dev

    # Platform config
    - name: docker-registry-base-url
      description: The docker registry base url with path to load the CI image for tekton task execution from
    - name: tekton-ci-image-name
      description: The image name to use for the automation run
      default: "ubuntu-ci-minimal"
    - name: tekton-ci-image-tag
      description: The image tag to use for the automation run
      default: "latest"

    # AUTOMATION REPOSITORY SECTION
    - name: automation-git-url
      description: |
        The git url of the automation repository to use (your fork of the kubementat repos address)
        e.g.: if you would use the kubementat default location: ssh://git@github.com:julweber/kubementat.git
    - name: automation-git-project-name
      description: |
        your local directory name for the repository
        In general this can be set to the default: "kubementat"
      default: "kubementat"
    - name: automation-git-revision
      description: |
        the git revision to checkout
        for the automation repository we are using master most of the time
      default: "master"
    - name: automation-git-server-host
      description: |
        this should match the hostname provided in automation-git-url
        this setting is used for configuring the ssh auth mechanism correctly
        e.g.: github.com
      default: github.com
    - name: automation-git-server-port
      description: |
        the git server ssh port
        this should match the port provided (or 22 if no port is provided) in automation-git-url
        this setting is used for configuring the ssh auth mechanism correctly
      default: "22"
    - name: automation-git-server-ssh-user
      description: |
        the git server ssh user
        this should match the username provided in automation-git-url
        this setting is used for configuring the ssh auth mechanism correctly
      default: "git"
    - name: automation-git-crypt-unlock
      description: |
        should a git-crypt unlock be executed on the checked out repo?
      default: "true"

    # task config
    - name: path-to-configuration-file
      description: |
        The path to the configuration file providing images to copy.
        This should contain platform_config
      default: "$(workspaces.workspace.path)/$(params.automation-git-project-name)/platform_config/$(params.environment)/mirrored_docker_images.json"
    - name: target-docker-registry-username
      description: The target docker registry username
      default: ""
      type: string
    - name: target-docker-registry-secret-key-filepath
      description: The docker registry secret filepath within the platform_config for logging into the target docker registry
      default: "$(workspaces.workspace.path)/$(params.automation-git-project-name)/platform_config/$(params.environment)/gcloud/docker-registry-internal-admin-gcloud-key.encrypted.json"
      type: string

  workspaces:
    - name: pipeline-workspace
  tasks:

    # clone automation source repo for deploy steps
    - name: git-clone-automation
      taskRef:
        name: git-clone-with-ssh-auth
      params:
        - name: git-url
          value: "$(params.automation-git-url)"
        - name: git-project-name
          value: "$(params.automation-git-project-name)"
        - name: git-revision
          value: "$(params.automation-git-revision)"
        - name: git-server-host
          value: "$(params.automation-git-server-host)"
        - name: git-server-port
          value: "$(params.automation-git-server-port)"
        - name: git-server-ssh-user
          value: "$(params.automation-git-server-ssh-user)"
        - name: git-crypt-unlock
          value: "$(params.automation-git-crypt-unlock)"
        - name: image
          value: "$(params.docker-registry-base-url)/$(params.tekton-ci-image-name):$(params.tekton-ci-image-tag)"
      workspaces:
        - name: workspace
          workspace: pipeline-workspace

    # view docker image details
    - name: skopeo-sync-images
      taskRef:
        name: skopeo-sync-images
      runAfter:
        - git-clone-automation
      params:
        - name: image
          value: "$(params.docker-registry-base-url)/$(params.tekton-ci-image-name):$(params.tekton-ci-image-tag)"

        - name: path-to-configuration-file
          value: "$(params.path-to-configuration-file)"

        - name: target-docker-registry-username
          value: "$(params.target-docker-registry-username)"
        - name: target-docker-registry-secret-key-filepath
          value: "$(params.target-docker-registry-secret-key-filepath)"

        
      workspaces:
        - name: workspace
          workspace: pipeline-workspace
