#!/usr/bin/env python3

import os
import click

class Config(object):
    def __init__(self):
        self.home = os.path.abspath(os.path.dirname(__file__))
        self.kubementat_main_dir = os.path.normpath(os.path.join(self.home, '../'))

from commands import tunnels
from commands import tekton
from commands import kubementat
from commands import utilities
from commands import helm

@click.group(help='Kubementat CLI')
@click.pass_context
def main(ctx):
    ctx.obj = Config()

if __name__ == '__main__':
    main.add_command(kubementat.initialize)
    main.add_command(kubementat.install)
    main.add_command(kubementat.uninstall)
    main.add_command(kubementat.setup_secrets)
    main.add_command(kubementat.setup_docker_registry_access)


    # tunnels
    main.add_command(tunnels.tunnel_pod)
    main.add_command(tunnels.tunnel_grafana)
    main.add_command(tunnels.tunnel_tekton)
    main.add_command(tunnels.tunnel_polaris)

    # k dashboard
    main.add_command(tunnels.login_kubernetes_dashboard)

    # tekton
    main.add_command(tekton.run_pipeline)
    main.add_command(tekton.cleanup_pipeline_runs)
    main.add_command(tekton.setup_pipelines)
    main.add_command(tekton.setup_triggers)
    main.add_command(tekton.list)
    main.add_command(tekton.uninstall_pipelines)
    
    # helm
    main.add_command(helm.helmfile_apply)

    # utilities
    main.add_command(utilities.run_ci_container)
    main.add_command(utilities.run_script)

    main()