# EVENT LISTENER RESOURCE FOR GITHUB TRIGGER
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: APP_NAME_PLACEHOLDER-TEAM_PLACEHOLDER-event-listener
spec:
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-trigger-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        # - ref:
        #     name: "cel"
        #   params:
        #     - name: "filter"
        #       value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: APP_NAME_PLACEHOLDER-TEAM_PLACEHOLDER-trigger-binding
      template:
        ref: APP_NAME_PLACEHOLDER-TEAM_PLACEHOLDER-trigger-template

  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-sa
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"