apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline-ci-images-run
spec:
  pipelineRef:
    name: build-pipeline-ci-images
  serviceAccountName: "HELM_DEPLOYER_SERVICE_ACCOUNT_NAME_PLACEHOLDER"
  timeout: 15m
  params:
    - name: docker-registry-base-url
      value: DOCKER_REGISTRY_BASE_URL_PLACEHOLDER
    - name: tekton-ci-image-name
      value: "TEKTON_CI_IMAGE_NAME_PLACEHOLDER"
    - name: tekton-ci-image-tag
      value: "TEKTON_CI_IMAGE_TAG_PLACEHOLDER"

    - name: automation-git-project-name
      value: "AUTOMATION_GIT_PROJECT_NAME_PLACEHOLDER"
    - name: automation-git-revision
      value: "AUTOMATION_GIT_REVISION_PLACEHOLDER"
    - name: automation-git-server-host
      value: "AUTOMATION_GIT_SERVER_HOST_PLACEHOLDER"
    - name: automation-git-server-port
      value: "AUTOMATION_GIT_SERVER_PORT_PLACEHOLDER"
    - name: automation-git-server-ssh-user
      value: "AUTOMATION_GIT_SERVER_SSH_USER_PLACEHOLDER"
    - name: automation-git-url
      value: "AUTOMATION_GIT_URL_PLACEHOLDER"
    - name: automation-git-crypt-unlock
      value: "false"

    - name: push-image-tag
      value: "TEKTON_CI_IMAGE_TAG_PLACEHOLDER"

  workspaces:
    - name: pipeline-workspace # this workspace name must be declared in the Pipeline
      volumeClaimTemplate:
        spec:
          storageClassName: STORAGE_CLASS_PLACEHOLDER
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 100Mi