apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline-public-ci-images-run
spec:
  pipelineRef:
    name: build-pipeline-public-ci-images
  serviceAccountName: helm-deployer-sa
  timeout: 15m
  params:
    - name: docker-registry-base-url
      value: DOCKER_REGISTRY_BASE_URL_PLACEHOLDER
    - name: tekton-ci-image-name
      value: "TEKTON_CI_IMAGE_NAME_PLACEHOLDER"
    - name: tekton-ci-image-tag
      value: "TEKTON_CI_IMAGE_TAG_PLACEHOLDER"
    - name: push-image-url
      value: julianweberdev/ubuntu-minimal-test
    - name: push-image-tag
      value: test
  workspaces:
    - name: pipeline-workspace # this workspace name must be declared in the Pipeline
      volumeClaimTemplate:
        spec:
          storageClassName: STORAGE_CLASS_PLACEHOLDER
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 100Mi