# EVENT LISTENER RESOURCE FOR GITLAB TRIGGER
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: APP_NAME_PLACEHOLDER-TEAM_PLACEHOLDER-event-listener
spec:
  triggers:
    - name: push-trigger
      interceptors:
        - gitlab:
            secretRef:
              secretName: gitlab-trigger-webhook-secret
              secretKey: secret
            eventTypes:
              - Push Hook
      bindings:
      - ref: APP_NAME_PLACEHOLDER-TEAM_PLACEHOLDER-trigger-binding
      template:
        ref: APP_NAME_PLACEHOLDER-TEAM_PLACEHOLDER-trigger-template

  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-sa
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"