# For reference:
# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml

# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:
# example adds prometheus-blackbox-exporter scrape config
extraScrapeConfigs: |
 - job_name: 'prometheus-blackbox-exporter'
   metrics_path: /probe
   params:
     module: [http_2xx]
   static_configs:
     - targets:
       - https://github.com/julweber
   relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: prometheus-blackbox-exporter.prometheus.svc.cluster.local:9115