apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: input-example-task-run
spec:
  taskRef:
    name: input-example-task
  params:
    - name: filename
      value: values.yaml.example
  resources:
    inputs:
      - name: git-source
        resourceRef:
          name: git-concourse-kubernetes-poc